apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    app: web-logs  # Correspond au label "app" dans le pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088  # Port exposé par le conteneur Flask
