apiVersion: v1
kind: Pod
metadata:
  name: web-logs-pod
  labels:
    app: web-logs
spec:
  containers:
  - name: flask-app
    image: simple-app-crud-psql-application:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8088
    env:
    - name: DATABASE_HOST
      value: "postgres-db.database.svc.cluster.local"
    - name: DATABASE_DATABASE
      value: "messages"
    - name: DATABASE_USER
      value: "appcrud"
    - name: DATABASE_PASSWORD
      value: "1234321"
  - name: log-collector
    image: busybox
    command: ["sh", "-c", "while true; do echo 'Collecting logs...'; sleep 10; done"]
